version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "9000:9000"
  nginx:
    build: ./requirements/nginx
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:8080"
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/wp